BEGIN;

TRUNCATE TABLE "pays"; 

INSERT INTO pays ("nom", "iso3", "capitale") VALUES
('Afghanistan', 'AFG', 'Kaboul'),
('Afrique du Sud', 'ZAF', 'Prétoria'),
('Albanie', 'ALB', 'Tirana'),
('Algérie', 'DZA', 'Alger'),
('Allemagne','DEU', 'Berlin'),
('Andorre','AND', 'Andorre-la-Vieille'),
('Angola', 'AGO', 'Luanda'),
('Anguilla', 'AIA', 'The Valley'),
('Antigua-et-Barbuda', 'ATG', 'Saint John''s'),
('Arabie saoudite', 'SAU', 'Riyad'),
('Argentine', 'ARG', 'Buenos Aires'),
('Arménie', 'ARM', 'Erevan'),
('Australie', 'AUS', 'Canberra'),
('Autriche', 'AUT', 'Vienne'),
('Azerbaïdjan', 'AZE', 'Bakou'),
('Bahamas', 'BHS', 'Nassau'),
('Bahreïn', 'BHR', 'Manama'),
('Bangladesh', 'BGD', 'Dacca'),
('Barbade', 'BRB', 'Bridgetown'),
('Belgique', 'BEL', 'Bruxelles'),
('Bélize', 'BLZ', 'Belmopan'),
('Bénin', 'BEN', 'Porto-Novo'),
('Bhoutan', 'BTN', 'Thimphou'),
('Biélorussie', 'BLR', 'Minsk'),
('Birmanie', 'MMR', 'Naypyidaw'),
('Bolivie', 'BOL', 'Sucre / La Paz'),
('Bosnie-Herzégovine', 'BIH', 'Sarajevo'),
('Botswana', 'BWA', 'Gaborone'),
('Brésil', 'BRA','Brasilia'),
('Brunei', 'BRN', 'Bandar Seri Begawan'),
('Bulgarie', 'BGR', 'Sofia'),
('Burkina Faso', 'BFA', 'Ouagadougou'),
('Burundi','BDI','Gitega'),
('Cambodge', 'KHM','Phnom Penh'),
('Cameroun', 'CMR', 'Yaoundé'),
('Canada', 'CAN', 'Ottawa'),
('Cap-Vert', 'CPV','Praia'),
('République centrafricaine', 'CAF', 'Bangui'),
('Chili', 'CHL', 'Santiago'),
('Chine', 'CHN', 'Pékin'),
('Chypre', 'CYP','Nicosie'),
('Colombie', 'COL','Bogota'),
('Comores', 'COM', 'Moroni'),
('Congo', 'COG', 'Brazzaville'),
('République démocratique du Congo', 'COD','Kinshasa'),
(')', 'COK', 'Avarua'),
('Corée du Nord','PRK', 'Pyongyang'),
('Corée du Sud','KOR','Séoul'),
('Costa Rica','CRI','San José'),
('Côte d''Ivoire','CIV','Yamoussoukro'),
('Croatie','HRV', 'Zagreb'),
('Cuba','CUB','La Havane'),
('Danemark','DNK', 'Copenhague'),
('Djibouti','DJI','Djibouti'),
('République dominicaine', 'DOM','Saint-Domingue'),
('Dominique','DMA', 'Roseau'),
('Égypte', 'EGY', 'Le Caire'),
('Émirats arabes unis', 'ARE', 'Abou Dabi'),
('Équateur','ECU', 'Quito'),
('Érythrée', 'ERI', 'Asmara'),
('Espagne', 'ESP', 'Madrid'),
('Estonie', 'EST', 'Tallinn'),
('Eswatini', 'SWZ', 'Mbabané'),
('États-Unis', 'USA', 'Washington'),
('Éthiopie', 'ETH', 'Addis Abeba'),
('Fidji', 'FJI','Suva'),
('Finlande', 'FIN',  'Helsinki'),
('France','FRA','Paris'),
('Gabon', 'GAB','Libreville'),
('Gambie', 'GMB', 'Banjul'),
('Géorgie','GEO', 'Tbilissi'),
('Ghana', 'GHA', 'Accra'),
('Grèce', 'GRC', 'Athènes'),
('Grenade','GRD', 'Saint-Georges'),
('Groenland', 'GRL', 'Nuuk'),
('Guadeloupe', 'GLP', 'Chef-lieu : Basse-Terre'),
('Guatémala', 'GTM','Guatémala'),
('Guinée','GIN','Conakry'),
('Guinée équatoriale', 'GNQ', 'Malabo'),
('Guinée-Bissau', 'GNB', 'Bissao'),
('Guyana', 'GUY', 'Georgetown'),
('Guyane française', 'GUF', 'Chef-lieu : Cayenne'),
('Haïti', 'HTI', 'Port-au-Prince'),
('Honduras', 'HND','Tégucigalpa'),
('Hongrie', 'HUN', 'Budapest'),
('Îles Turques-et-Caïques', 'TCA', 'Cockburn Town'),
('Îles Vierges des États-Unis', 'VIR', 'Charlotte-Amélie'),
('Îles Vierges britanniques', 'VGB', 'Road Town'),
('Inde','IND','New Delhi'),
('Indonésie','IDN', 'Jakarta'),
('Irak', 'IRQ', 'Bagdad'),
('Iran', 'IRN', 'Téhéran'),
('Irlande', 'IRL', 'Dublin'),
('Islande', 'ISL', 'Reykjavik'),
('Israël', 'ISR', ''),
('Italie', 'ITA', 'Rome'),
('Jamaïque', 'JAM', 'Kingston'),
('Japon','JPN', 'Tokyo'),
('Jordanie', 'JOR', 'Amman'),
('Kazakhstan', 'KAZ','Nour-Soultan'),
('Kénya', 'KEN', 'Nairobi'),
('Kirghizistan', 'KGZ', 'Bichkek'),
-- ('Kiribati', 'KIR', 'Bairiki'),
('Kosovo', 'KOS', 'Pristina'),
('Koweït','KWT', 'Koweït'),
('Laos','LAO', 'Vientiane'),
('Lésotho', 'LSO', 'Maséru'),
('Lettonie', 'LVA', 'Riga'),
('Liban', 'LBN','Beyrouth'),
('Libéria', 'LBR', 'Monrovia'),
('Libye','LBY', 'Tripoli'),
('Liechtenstein', 'LIE', 'Vaduz'),
('Lituanie', 'LTU','Vilnius'),
('Luxembourg', 'LUX',  'Luxembourg'),
('Macédoine du Nord','MKD', 'Skopje'),
('Madagascar', 'MDG',  'Antananarivo (Tananarive)'),
('Malaisie', 'MYS', 'Kuala Lumpur'),
('Malawi', 'MWI','Lilongwé'),
('Maldives','MDV', 'Malé'),
('Mali','MLI','Bamako'),
('Malte', 'MLT','La Valette'),
('Maroc', 'MAR', 'Rabat'),
('Martinique', 'MTQ', 'Chef-lieu : Fort-de-France'),

('Îles Malouines', 'FLK', 'Port Stanley'),
('Maurice', 'MUS','Port-Louis'),
('Mauritanie', 'MRT', 'Nouakchott'),
('Mexique', 'MEX', 'Mexico'),
-- ('Micronésie', 'FSM', 'Palikir'),
('Moldavie','MDA', 'Chisinau'),
('Monaco','MCO', 'Monaco'),
('Mongolie', 'MNG', 'Oulan-Bator'),
('Monténégro', 'MNE','Podgorica'),
('Mozambique', 'MOZ', 'Maputo'),
('Namibie', 'NAM', 'Windhoek'),
('Nauru',  'NRU','Yaren'),
('Népal', 'NPL', 'Katmandou'),
('Nicaragua', 'NIC', 'Managua'),
('Niger', 'NER', 'Niamey'),
('Nigéria','NGA','Abuja'),
-- ('Niue','NIU', 'Alofi'),
('Norvège', 'NOR','Oslo'),
('Nouvelle-Calédonie','NCL', 'Nouméa'),
('Nouvelle-Zélande', 'NZL', 'Wellington'),
('Oman', 'OMN','Mascate'),
('Ouganda','UGA', 'Kampala'),
('Ouzbékistan', 'UZB', 'Tachkent'),
('Pakistan','PAK', 'Islamabad'),
('Palaos','PLW','Melekeok'),
('Panama', 'PAN','Panama'),
('Papouasie-Nouvelle-Guinée', 'PNG', 'Port Moresby'),
('Paraguay', 'PRY', 'Assomption (Asuncion)'),
('Pays-Bas', 'NLD', 'Amsterdam'),
('Pérou', 'PER','Lima'),
('Philippines', 'PHL', 'Manille'),
('Pologne','POL','Varsovie'),
('Portugal', 'PRT', 'Lisbonne'),
('Porto Rico', 'PRI', 'San Juan'),
('Qatar','QAT', 'Doha'),
('Réunion', 'REU', 'Chef-lieu : Saint-Denis'),
('Roumanie', 'ROU','Bucarest'),
('Royaume-Uni', 'GBR', 'Londres'),
('Russie','RUS', 'Moscou'),
('Rwanda', 'RWA', 'Kigali'),
('Sahara occidental', 'ESH', ''),
('Saint-Christophe-et-Niévès', 'KNA', 'Basseterre'),
('Sainte-Lucie', 'LCA', 'Castries'),
('Saint-Marin', 'SMR', 'Saint-Marin'),
('Saint-Vincent-et-les-Grenadines', 'VCT', 'Kingstown'),
('Saint-Martin', 'MAF', ''),
('Îles Salomon','SLB','Honiara'),
('Salvador', 'SLV', 'San Salvador'),
('Samoa','WSM','Apia'),
('Sao Tomé-et-Principe', 'STP','Sao Tomé'),
('Sénégal', 'SEN', 'Dakar'),
('Serbie', 'SRB', 'Belgrade'),
('Seychelles', 'SYC', 'Victoria'),
('Sierra Leone', 'SLE','Freetown'),
('Singapour','SGP', 'Singapour'),
('Slovaquie', 'SVK','Bratislava'),
('Slovénie', 'SVN', 'Ljubljana'),
('Somalie','SOM', 'Mogadiscio'),
('Soudan', 'SDN', 'Khartoum'),
('Soudan du Sud', 'SDS', 'Djouba'),
('Sri Lanka', 'LKA','Sri Jayewardenepura-Kotte'),
('Suède', 'SWE', 'Stockholm'),
('Suisse', 'CHE', 'Berne'),
('Suriname','SUR', 'Paramaribo'),
('Syrie', 'SYR', 'Damas'),
('Tadjikistan', 'TJK', 'Douchanbé'),
('Tanzanie', 'TZA', 'Dodoma'),
('Taiwan', 'TWN', 'Taipei'),
('Tchad', 'TCD', 'Ndjamena'),
('République tchèque', 'CZE', 'Prague'),
('Thaïlande', 'THA', 'Bangkok'),
('Timor oriental', 'TLS', 'Dili'),
('Togo', 'TGO', 'Lomé'),
('Tonga', 'TON', 'Nuku''alofa'),
('Trinité-et-Tobago', 'TTO', 'Port-d''Espagne (Port of Spain)'),
('Tunisie', 'TUN', 'Tunis'),
('Turkménistan', 'TKM', 'Achgabat'),
('Turquie', 'TUR','Ankara'),
('Tuvalu', 'TUV', 'Vaiaku'),
('Ukraine', 'UKR', 'Kiev'),
('Uruguay', 'URY', 'Montévidéo'),
('Vanuatu', 'VUT','Port-Vila'),
('Vatican', 'VAT', ''),
('Vénézuéla', 'VEN', 'Caracas'),
('Vietnam', 'VNM', 'Hanoï'),
('Yémen', 'YEM', 'Sanaa'),
('Zambie',  'ZMB', 'Lusaka'),
('Zimbabwé', 'ZWE', 'Hararé');

TRUNCATE TABLE "paysbyiso2"; 

INSERT INTO paysbyiso2 ("nom", "iso2") VALUES
('Afghanistan', 'AF'),
('Îles Åland', 'AX'),
('Albanie', 'AL'),
('Algérie', 'DZ'),
('Samoa américaines', 'AS'),
('Andorre', 'AD'),
('Angola', 'AO'),
('Anguilla', 'AI'),
('Antarctique', 'AQ'),
('Antigua-et-Barbuda', 'AG'),
('Argentine', 'AR'),
('Arménie', 'AM'),
('Aruba', 'AW'),
('Australie', 'AU'),
('Autriche', 'AT'),
('Azerbaïdjan', 'AZ'),
('Bahamas', 'BS'),
('Bahreïn', 'BH'),
('Bangladesh', 'BD'),
('Barbade', 'BB'),
('Biélorussie', 'BY'),
('Belgique', 'BE'),
('Bélize', 'BZ'),
('Bénin', 'BJ'),
('Bermudes', 'BM'),
('Bhoutan', 'BT'),
('Bolivie', 'BO'),
('Bosnie-Herzégovine', 'BA'),
('Botswana', 'BW'),
('Île Bouvet', 'BV'),
('Brésil', 'BR'),
('British Virgin Islands', 'VG'),
('Territoire britannique de l’Océan Indien', 'IO'),
('Brunei', 'BN'),
('Bulgarie', 'BG'),
('Burkina Faso', 'BF'),
('Burundi', 'BI'),
('Cambodge', 'KH'),
('Cameroun', 'CM'),
('Canada', 'CA'),
('Cap-Vert', 'CV'),
('Iles Cayman', 'KY'),
('République centrafricaine', 'CF'),
('Tchad', 'TD'),
('Chili', 'CL'),
('Chine', 'CN'),
('Hong Kong', 'HK'),
('Macao', 'MO'),
('Île Christmas', 'CX'),
('Îles Cocos', 'CC'),
('Colombie', 'CO'),
('Comores', 'KM'),
('Congo', 'CG'),
('République démocratique du Congo', 'CD'),
-- ('Îles Cook', 'CK'),
('Costa Rica', 'CR'),
('Côte d''Ivoire', 'CI'),
('Croatie', 'HR'),
('Cuba', 'CU'),
('Chypre', 'CY'),
('République tchèque', 'CZ'),
('Danemark', 'DK'),
('Djibouti', 'DJ'),
('Dominique', 'DM'),
('République dominicaine', 'DO'),
('Équateur', 'EC'),
('Égypte', 'EG'),
('Salvador', 'SV'),
('Guinée équatoriale', 'GQ'),
('Érythrée', 'ER'),
('Estonie', 'EE'),
('Éthiopie', 'ET'),
('Îles Malouines', 'FK'),
('Îles Féroé', 'FO'),
('Fidji', 'FJ'),
('Finlande', 'FI'),
('France', 'FR'),
('Guyane française', 'GF'),
('Polynésie française', 'PF'),
('Terres australes et antarctiques françaises', 'TF'),
('Gabon', 'GA'),
('Gambie', 'GM'),
('Géorgie', 'GE'),
('Allemagne', 'DE'),
('Ghana', 'GH'),
('Gibraltar', 'GI'),
('Grèce', 'GR'),
('Groenland', 'GL'),
('Grenade', 'GD'),
('Guadeloupe', 'GP'),
('Guam', 'GU'),
('Guatémala', 'GT'),
('Guernesey', 'GG'),
('Guinée', 'GN'),
('Guinée-Bissau', 'GW'),
('Guyana', 'GY'),
('Haïti', 'HT'),
('Îles Heard-et-MacDonald', 'HM'),
('Saint-Siège (Vatican)', 'VA'),
('Honduras', 'HN'),
('Hongrie', 'HU'),
('Islande', 'IS'),
('Inde', 'IN'),
('Indonésie', 'ID'),
('Iran', 'IR'),
('Irak', 'IQ'),
('Irlande', 'IE'),
('Ile de Man', 'IM'),
('Israël', 'IL'),
('Italie', 'IT'),
('Jamaïque', 'JM'),
('Japon', 'JP'),
('Jersey', 'JE'),
('Jordanie', 'JO'),
('Kazakhstan', 'KZ'),
('Kénya', 'KE'),
-- ('Kiribati', 'KI'),
('Corée du Nord', 'KP'),
('Corée du Sud', 'KR'),
('Koweït', 'KW'),
('Kosovo', 'XK'),
('Kirghizistan', 'KG'),
('Laos', 'LA'),
('Lettonie', 'LV'),
('Liban', 'LB'),
('Lésotho', 'LS'),
('Libéria', 'LR'),
('Libye', 'LY'),
('Liechtenstein', 'LI'),
('Lituanie', 'LT'),
('Luxembourg', 'LU'),
('Macédoine du Nord', 'MK'),
('Madagascar', 'MG'),
('Malawi', 'MW'),
('Malaisie', 'MY'),
('Maldives', 'MV'),
('Mali', 'ML'),
('Malte', 'MT'),
('Martinique', 'MQ'),
('Mauritanie', 'MR'),
('Maurice', 'MU'),
('Mayotte', 'YT'),
('Mexique', 'MX'),
-- ('Micronésie', 'FM'),
('Moldavie', 'MD'),
('Monaco', 'MC'),
('Mongolie', 'MN'),
('Monténégro', 'ME'),
('Montserrat', 'MS'),
('Maroc', 'MA'),
('Mozambique', 'MZ'),
('Birmanie', 'MM'),
('Namibie', 'NA'),
('Nauru', 'NR'),
('Népal', 'NP'),
('Pays-Bas', 'NL'),
('Nouvelle-Calédonie', 'NC'),
('Nouvelle-Zélande', 'NZ'),
('Nicaragua', 'NI'),
('Niger', 'NE'),
('Nigéria', 'NG'),
-- ('Niue', 'NU'),
('Île Norfolk', 'NF'),
('Îles Mariannes du Nord', 'MP'),
('Norvège', 'NO'),
('Oman', 'OM'),
('Pakistan', 'PK'),
('Palau', 'PW'),
('Palestine', 'PS'),
('Panama', 'PA'),
('Papouasie-Nouvelle-Guinée', 'PG'),
('Paraguay', 'PY'),
('Pérou', 'PE'),
('Philippines', 'PH'),
('Pitcairn', 'PN'),
('Pologne', 'PL'),
('Portugal', 'PT'),
('Porto Rico', 'PR'),
('Qatar', 'QA'),
('Réunion', 'RE'),
('Roumanie', 'RO'),
('Russie', 'RU'),
('Rwanda', 'RW'),
('Saint-Barthélemy', 'BL'),
('Sainte-Hélène', 'SH'),
('Saint-Christophe-et-Niévès', 'KN'),
('Sainte-Lucie', 'LC'),
('Saint-Martin', 'SX'),
('Saint-Pierre-et-Miquelon', 'PM'),
('Saint-Vincent-et-les-Grenadines', 'VC'),
-- ('Samoa', 'WS'),
('Saint-Marin', 'SM'),
('Sao Tomé-et-Principe', 'ST'),
('Arabie saoudite', 'SA'),
('Sénégal', 'SN'),
('Serbie', 'RS'),
('Seychelles', 'SC'),
('Sierra Leone', 'SL'),
('Singapour', 'SG'),
('Slovaquie', 'SK'),
('Slovénie', 'SI'),
('Îles Salomon', 'SB'),
('Somalie', 'SO'),
('Afrique du Sud', 'ZA'),
('Géorgie du Sud et les îles Sandwich du Sud', 'GS'),
('Soudan du Sud', 'SS'),
('Espagne', 'ES'),
('Sri Lanka', 'LK'),
('Soudan', 'SD'),
('Suriname', 'SR'),
('Svalbard et Jan Mayen', 'SJ'),
('Eswatini', 'SZ'),
('Suède', 'SE'),
('Suisse', 'CH'),
('Syrie', 'SY'),
('Taiwan', 'TW'),
('Tadjikistan', 'TJ'),
('Tanzanie', 'TZ'),
('Thaïlande', 'TH'),
('Timor oriental', 'TL'),
('Togo', 'TG'),
('Tokelau', 'TK'),
('Tonga', 'TO'),
('Trinité-et-Tobago', 'TT'),
('Tunisie', 'TN'),
('Turquie', 'TR'),
('Turkménistan', 'TM'),
('Îles Turques-et-Caïques', 'TC'),
-- ('Tuvalu', 'TV'),
('Ouganda', 'UG'),
('Ukraine', 'UA'),
('Émirats arabes unis', 'AE'),
('Royaume-Uni', 'GB'),
('États-Unis', 'US'),
('Îles mineures éloignées des États-Unis', 'UM'),
('Uruguay', 'UY'),
('Ouzbékistan', 'UZ'),
('Vanuatu', 'VU'),
('Vénézuéla', 'VE'),
('Vietnam', 'VN'),
('Îles Vierges britanniques', 'VG'),
('Îles Vierges des États-Unis', 'VI'),
('Wallis-et-Futuna', 'WF'),
('Sahara occidental', 'EH'),
('Yémen', 'YE'),
('Zambie', 'ZM'),
('Zimbabwé', 'ZW');

TRUNCATE TABLE "code_requete"; 

INSERT INTO "code_requete" ("iso2") VALUES
('aa');

COMMIT;